language: go
sudo: false
go:
 - stable
before_install:
 - go get github.com/mattn/goveralls
 - $HOME/gopath/bin/goveralls -service=travis-ci
script:
- make buildcmd
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: Rm57E9u5/Ll+pIFkpzF9slbsV/C5aXpDK3CCq4oJBuaLIFEmEk4z8M1M3EuRanMlmZv51CHQOFjCu2D+AFgduLEfetysywrQsGFLuwZWAOXW734wPbgOXygugzU8j1/BnfbOfIuyzyIHNM6a5qm0Lp8YQ9UIkcCBwSYo2Ie9dZsprBBvHofzmJsc8IFZ37xzUFux4AqFtrf4HmHxooePuZbRn+OHn1z7zmOmidW0CK/IG8gHOKm0PAhbowX7FBUqieMe24LesAQvrUEI4G+u1qL7LBORpinPMJk2S1ECGnVmHVzEIHdWsOFIPRvoNld2BOrYT/zgA3OeePJJvUiyrVOBaqApEPxifXlNgEJVgBtDvvEpadXXsB5ecJ7RSU0XleVb2yn3P6GoKPvwfCBrOW6o12cMh9aPpLn0lt9bEw5HXIbrCwOQG/F2mMPLGa2sfztIQQAjUUPqXcM8WAPrAsY1UF67jgKBLAnrV9FK4p7h4ZrRH/caIpzmt7KRK8X446qYs+6WDHnSHtdbzl0f6Il5ae0BDxvDKcGoKTMN5/Ojp5vVO+Fof6/9pzNJRk/chiYdgjIYUkpjj5MHeX1yenGs6sBeejeGOXGw12Z/f1VwxFRwDPHIzYCk56s0Tgw8OaSfYz+tpkhQndTkItGU+ZJi96jGCJvL7a/OInUcH14=
  file:
    - bin/feiertage_linux_x86_64
    - bin/feiertage_osx_x86_64
    - bin/feiertage_win32
    - bin/feiertage_win64
  on:
    repo: wlbr/feiertage
    tags: true
after_deploy: make clean
