language: go
sudo: false
go:
 - stable
before_install:
 - go get github.com/mattn/goveralls
 - $HOME/gopath/bin/goveralls -service=travis-ci
script:
 - make buildcmd
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: Qe49LSp0eIOiAzQHpu8bZK3vPdjXiMdbY5uDGyiGdZ34hpMISxd/QrEist6u+FkwbAtoYqIGCKLWRsGCP5CxCl7slob1lSSF5PjCE8CbHSz/Tm4mEQMvhsvh+Xwg1AZT+KS8kgz2okzi0wIBurA4lyvXBwv7dXzwxHMj3zJ7SbgR9xmnu4wWt5JZw2jZadgQnNFifg7jqVO9l8AUjcOkFrEomVR65R0b1bGfpdqkz2z6cPzFnJAuUVZvVTuoG8TrOWyN8+4ncSqnegiwsR+nAGgAzK7/RWfBfaWqT4uYcwueH8/l/0FwovxOeNhhsdZ6f1yxYIFGqptl+QSnH3eBKXAL+BzrF0jhPhOLMOozhQ2nEblLpliJzveXbHFWhIznyFbdEo1dHPvswKUXsKAVbmEdQeNLB5mA+acwVilQWnrvZLM291Wue0FJvCXmwtzaETAi8XJzVCxAgYhQEP/iN8CXh42AF2Lj1FbP4ONCfLfdb5vgwp5pVmdt5R5DDHpP9NiHn/ZY1qAUEawn1ZXXholJAqkjR3eyBY1xsdtVu9SfryITCTMEK1N8dDVJTeW0uamn2Q6g0UK0/l4QlvBQR/Fs3SWsw7mNZk4GN0DLr2GHnf0ExUCg6e1Gn8nnNs7KuWY/M8XEXmn56AoNWQOLBTF6ssVsIO3lNUKyjlocOVA=
  file:
    - bin/feiertage_linux_x86_64
    - bin/feiertage_osx_x86_64
    - bin/feiertage_win32
    - bin/feiertage_win64
  on:
    repo: wlbr/feiertage
    tags: false
after_deploy: make clean
