language: go
sudo: false
go:
 - stable
before_install:
 - go get github.com/mattn/goveralls
 - $HOME/gopath/bin/goveralls -service=travis-ci
script:
- make buildcmd
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: PZN7yqcXMs6NxuIqaUBFgO93BHqr9s0MlhVNnizsyMbYmvzSgxkwhvSanOWV5GeFQOlia/XmiGabcXbZJvKF4/+oMU7C7dcdCXZU2zOIbPvSI4Zypiaf4p8RWG7JgF/+4bWl7iX19vea++hWGrt6DQEfzv2ElfhcsbedKEQ4iemCngmzUZqaKFzWHIf/KB8hGVe9a2r//0tZ1uyFrkVJNjl+QakBaz+ywvEAzSjo+lapgVLgBgkElZQzfhPdUvTNeh358qL3tkURYzdjv8hYjgmrxA+d6pASr2ggOtQcVWibrNQ5HLAgRRdIHB55KwcTOaOzZT0ua43RChMvJxqzuX3/h38JXky32UE3d3V8+f4vBgndNbzyIMAcANgB+SE9RFHmtfjNCedDHI7kg5ihgTtyUMWnMFoBgNPBSbTasN0U9MhMY2/p2+OuV5uGNqTI3YeUt0KJ+S00OrylhIae15Mv9cEzEIO2Ykki0mg8inehIIpIuZWBHYBe9gp/v3rXMdptR2k1wto4VXvNG6F1cKV08d1/DD6HxYfBITjRXKBdaHEuzKfIgycAOGYomLqyDuk6QpzXx3Q4iMUfXLXIcK3twit8dHqizdjHRCfm4Jsmq0enXzP7uIMPJr/E+cUL52/Fr1iIXGNZ9baMCak9AIsLksmzWbwtDzM+gMewz3k=
  file:
    - bin/feiertage_linux_x86_64
    - bin/feiertage_osx_x86_64
    - bin/feiertage_win32
    - bin/feiertage_win64
  on:
    repo: wlbr/feiertage
    tags: false
after_deploy: make clean
